export const AVAILABLE_BLOG_TAGS = [
  // Stack
  'Angular',
  'TypeScript',
  'NestJS',
  'PostgreSQL',
  'Docker',
  'DevOps',
  'IndexedDB',
  'Web Crypto API',
  'Zod',
  'RxJS',
  // Sécurité & cryptographie
  'Sécurité',
  'Sécurité web',
  'Chiffrement',
  'Chiffrement côté client',
  'AES-256-GCM',
  'AES-KW',
  'PBKDF2',
  'E2EE',
  'Zero-knowledge',
  'Double enveloppe de clés',
  'Cryptographie',
  'OWASP',
  'XSS',
  'Données sensibles',
  'Données de santé',
  'RGPD',
  'Privacy by design',
  // Ingénierie
  'Architecture',
  'Tests',
  'SEO',
  'Audit de sécurité',
  "Retour d'expérience",
  // Parcours
  'Parcours',
  'Reconversion',
  'Carrière',
  'Industrie',
  'Métallurgie',
  'Autodidacte',
  'Full-Stack',
  // Projets & infra
  'DashFlow',
  'Auto-hébergement',
  'CI/CD',
  'GreenTech',
] as const;
