export const LUCIDE_TO_PRIMEICON: Readonly<Record<string, string>> = {
  'lucide-activity': 'pi-wave-pulse',
  'lucide-arrow-left': 'pi-arrow-left',
  'lucide-arrow-right': 'pi-arrow-right',
  'lucide-bar-chart-3': 'pi-chart-bar',
  'lucide-book-open': 'pi-book',
  'lucide-briefcase': 'pi-briefcase',
  'lucide-calendar': 'pi-calendar',
  'lucide-check': 'pi-check',
  'lucide-chevron-left': 'pi-chevron-left',
  'lucide-chevron-right': 'pi-chevron-right',
  'lucide-clock': 'pi-clock',
  'lucide-code-xml': 'pi-code',
  'lucide-compass': 'pi-compass',
  'lucide-cpu': 'pi-microchip',
  'lucide-credit-card': 'pi-credit-card',
  'lucide-download': 'pi-download',
  'lucide-external-link': 'pi-external-link',
  'lucide-eye': 'pi-eye',
  'lucide-file-text': 'pi-file',
  'lucide-github': 'pi-github',
  'lucide-graduation-cap': 'pi-graduation-cap',
  'lucide-home': 'pi-home',
  'lucide-laptop': 'pi-desktop',
  'lucide-layers': 'pi-clone',
  'lucide-layout-dashboard': 'pi-th-large',
  'lucide-lightbulb': 'pi-lightbulb',
  'lucide-linkedin': 'pi-linkedin',
  'lucide-loader-2': 'pi-spinner pi-spin',
  'lucide-lock': 'pi-lock',
  'lucide-log-out': 'pi-sign-out',
  'lucide-mail': 'pi-envelope',
  'lucide-map-pin': 'pi-map-marker',
  'lucide-menu': 'pi-bars',
  'lucide-message-square': 'pi-comment',
  'lucide-moon': 'pi-moon',
  'lucide-notebook-pen': 'pi-pencil',
  'lucide-panel-left-close': 'pi-angle-double-left',
  'lucide-panel-left-open': 'pi-angle-double-right',
  'lucide-pen-line': 'pi-pencil',
  'lucide-phone': 'pi-phone',
  'lucide-rocket': 'pi-send',
  'lucide-search': 'pi-search',
  'lucide-send': 'pi-send',
  'lucide-share-2': 'pi-share-alt',
  'lucide-shield-check': 'pi-shield',
  'lucide-shield-user': 'pi-shield',
  'lucide-sparkles': 'pi-sparkles',
  'lucide-star': 'pi-star',
  'lucide-sun': 'pi-sun',
  'lucide-trash-2': 'pi-trash',
  'lucide-user': 'pi-user',
  'lucide-users': 'pi-users',
  'lucide-wrench': 'pi-wrench',
  'lucide-x': 'pi-times',
  'lucide-zap': 'pi-bolt',
  'material-symbols-heart-smile': 'pi-heart-fill',
  spinners: 'pi-spinner pi-spin',
  'bi-twitter-x': 'pi-twitter',
  'bi-discord': 'pi-discord',
  'lucide-server': 'pi-server',
  'lucide-database': 'pi-database',
  'lucide-cloud': 'pi-cloud',
  'lucide-discord': 'pi-discord',
  'lucide-box': 'pi-box',
  'lucide-cog': 'pi-cog',
  'lucide-settings': 'pi-cog',
  'lucide-sitemap': 'pi-sitemap',
  'lucide-hammer': 'pi-hammer',
  'lucide-palette': 'pi-palette',
  'lucide-globe': 'pi-globe',
  'lucide-at-sign': 'pi-at',
  'lucide-heart': 'pi-heart',
  'lucide-target': 'pi-bullseye',
  'lucide-flag': 'pi-flag',
  'lucide-bolt': 'pi-bolt',
  'lucide-youtube': 'pi-youtube',
  'lucide-instagram': 'pi-instagram',
  'lucide-facebook': 'pi-facebook',
  'lucide-whatsapp': 'pi-whatsapp',
  'lucide-slack': 'pi-slack',
  'lucide-telegram': 'pi-telegram',
  'lucide-twitter': 'pi-twitter',
  'lucide-award': 'pi-trophy',
  'lucide-medal': 'pi-verified',
  'lucide-badge-check': 'pi-verified',
  'lucide-gem': 'pi-star',
  'lucide-goal': 'pi-bullseye',
  'lucide-crosshair': 'pi-bullseye',
  'lucide-clipboard-check': 'pi-clipboard',
  'lucide-clipboard-list': 'pi-clipboard',
  'lucide-list-checks': 'pi-check-square',
  'lucide-scan': 'pi-search',
  'lucide-binoculars': 'pi-search-plus',
  'lucide-telescope': 'pi-search-plus',
  'lucide-radar': 'pi-compass',
  'lucide-map': 'pi-map',
  'lucide-cloud-upload': 'pi-cloud-upload',
  'lucide-cloud-download': 'pi-cloud-download',
  'lucide-package': 'pi-box',
  'lucide-package-2': 'pi-box',
  'lucide-packages': 'pi-box',
  'lucide-boxes': 'pi-box',
  'lucide-container': 'pi-box',
  'lucide-ship': 'pi-send',
  'lucide-truck': 'pi-truck',
  'lucide-wifi': 'pi-wifi',
  'lucide-network': 'pi-sitemap',
  'lucide-workflow': 'pi-sitemap',
  'lucide-building': 'pi-building',
  'lucide-factory': 'pi-building',
  'lucide-warehouse': 'pi-building',
  valid: 'pi-verified',
  'spider-web': 'pi-sitemap',
};

/**
 * Fallback strategy: if the token has no explicit mapping, strip the known
 * prefix (lucide-, bi-, material-symbols-) and try `pi-<bareName>` — many
 * icon names (server, database, cloud, code, etc.) coincide between libraries.
 */
export function toPrimeIcon(token: string): string {
  const direct = LUCIDE_TO_PRIMEICON[token];
  if (direct) return direct;
  const bare = token.replace(/^(lucide|bi|material-symbols)-/, '');
  return `pi-${bare}`;
}
