#!/usr/bin/env node
// Reads the shared .env (../nest-portfolio-app/.env) and generates
// src/environments/environment.ts at build time. Run automatically via
// prestart / prebuild npm hooks. Never commit the generated file.
//
// Only PUBLIC-SAFE variables are inlined into the Angular bundle. Secrets
// like JWT_SECRET, S3_*, SMTP_PASS stay in the back .env, never injected here.
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const ENV_PATH = '../nest-portfolio-app/.env';

if (existsSync(ENV_PATH)) {
  // Node 20.12+ built-in: respects existing process.env, no dotenv dep needed
  process.loadEnvFile(ENV_PATH);
} else {
  console.warn(`⚠ ${ENV_PATH} not found — environment.ts will have empty values`);
}

const nodeEnv = process.env.NODE_ENV ?? 'development';

const env = {
  production: nodeEnv === 'production',
  sentry: {
    dsn: process.env.SENTRY_DSN ?? '',
    environment: nodeEnv,
    release: process.env.SENTRY_RELEASE ?? nodeEnv,
  },
};

const content = `// AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT, DO NOT COMMIT
// Source: ${ENV_PATH}
// Regenerated automatically on \`pnpm start\` / \`pnpm build\` via prestart/prebuild hooks.

export const environment = ${JSON.stringify(env, null, 2)};
`;

const out = 'src/environments/environment.ts';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, content);

console.log(
  `✓ Generated ${out} (DSN: ${env.sentry.dsn ? '[set]' : '[empty]'}, NODE_ENV: ${nodeEnv})`,
);
